export const DOCTOR_FETCH_PATIENT_REQUEST = 'DOCTOR_FETCH_PATIENT_REQUEST';
export const DOCTOR_FETCH_PATIENT_SUCCESS = 'DOCTOR_FETCH_PATIENT_SUCCESS';
export const DOCTOR_FETCH_PATIENT_FAIL = 'DOCTOR_FETCH_PATIENT_FAIL';

export const DOCTOR_GET_EXERCISE_REQUEST = 'DOCTOR_GET_EXERCISE_REQUEST';
export const DOCTOR_GET_EXERCISE_SUCCESS = 'DOCTOR_GET_EXERCISE_SUCCESS';
export const DOCTOR_GET_EXERCISE_FAIL = 'DOCTOR_GET_EXERCISE_FAIL';

export const DOCTOR_SET_EXERCISE_REQUEST = 'DOCTOR_SET_EXERCISE_REQUEST';
export const DOCTOR_SET_EXERCISE_SUCCESS = 'DOCTOR_SET_EXERCISE_SUCCESS';
export const DOCTOR_SET_EXERCISE_FAIL = 'DOCTOR_SET_EXERCISE_FAIL';

export const DOCTOR_CHECK_MEDICAL_RECORD_REQUEST =
  'DOCTOR_CHECK_MEDICAL_RECORD_REQUEST';
export const DOCTOR_CHECK_MEDICAL_RECORD_SUCCESS =
  'DOCTOR_CHECK_MEDICAL_RECORD_SUCCESS';
export const DOCTOR_CHECK_MEDICAL_RECORD_FAIL =
  'DOCTOR_CHECK_MEDICAL_RECORD_FAIL';

export const DOCTOR_CREATE_MEDICAL_RECORD_REQUEST =
  'DOCTOR_CREATE_MEDICAL_RECORD_REQUEST';
export const DOCTOR_CREATE_MEDICAL_RECORD_SUCCESS =
  'DOCTOR_CREATE_MEDICAL_RECORD_SUCCESS';
export const DOCTOR_CREATE_MEDICAL_RECORD_FAIL =
  'DOCTOR_CREATE_MEDICAL_RECORD_FAIL';

export const DOCTOR_RETRIEVE_MESSAGES_REQUEST =
  'DOCTOR_RETRIEVE_MESSAGES_REQUEST';
export const DOCTOR_RETRIEVE_MESSAGES_SUCCESS =
  'DOCTOR_RETRIEVE_MESSAGES_SUCCESS';
export const DOCTOR_RETRIEVE_MESSAGES_FAIL = 'DOCTOR_RETRIEVE_MESSAGES_FAIL';

export const DOCTOR_GET_HISTORY_REQUEST = 'DOCTOR_GET_HISTORY_REQUEST';
export const DOCTOR_GET_HISTORY_SUCCESS = 'DOCTOR_GET_HISTORY_SUCCESS';
export const DOCTOR_GET_HISTORY_FAIL = 'DOCTOR_GET_HISTORY_FAIL';

export const DOCTOR_REGISTER_DETAILS_REQUEST =
  'DOCTOR_REGISTER_DETAILS_REQUEST';
export const DOCTOR_REGISTER_DETAILS_SUCCESS =
  'DOCTOR_REGISTER_DETAILS_SUCCESS';
export const DOCTOR_REGISTER_DETAILS_FAIL = 'DOCTOR_REGISTER_DETAILS_FAIL';

export const DOCTOR_CHECK_DETAILS_EXISTS_REQUEST =
  'DOCTOR_CHECK_DETAILS_EXISTS_REQUEST';
export const DOCTOR_CHECK_DETAILS_EXISTS_SUCCESS =
  'DOCTOR_CHECK_DETAILS_EXISTS_SUCCESS';
export const DOCTOR_CHECK_DETAILS_EXISTS_FAIL =
  'DOCTOR_CHECK_DETAILS_EXISTS_FAIL';

export const DOCTOR_GET_MULTIPLE_PATIENTS_REQUEST =
  'DOCTOR_GET_MULTIPLE_PATIENTS_REQUEST';
export const DOCTOR_GET_MULTIPLE_PATIENTS_SUCCESS =
  'DOCTOR_GET_MULTIPLE_PATIENTS_SUCCESS';
export const DOCTOR_GET_MULTIPLE_PATIENTS_FAIL =
  'DOCTOR_CHECK_DETAILS_EXISTS_FAIL';
export const DOCTOR_GET_MULTIPLE_PATIENTS_CLEAR =
  'DOCTOR_CHECK_DETAILS_EXISTS_CLEAR';

export const DOCTOR_UPDATE_EXERCISE_REQUEST = 'DOCTOR_UPDATE_EXERCISE_REQUEST';
export const DOCTOR_UPDATE_EXERCISE_SUCCESS = 'DOCTOR_UPDATE_EXERCISE_SUCCESS';
export const DOCTOR_UPDATE_EFFECT_SUCCESS = 'DOCTOR_UPDATE_EFFECT_SUCCESS';
export const DOCTOR_UPDATE_EXERCISE_FAIL = 'DOCTOR_CHECK_DETAILS_EXISTS_FAIL';
export const DOCTOR_UPDATE_EXERCISE_CLEAR = 'DOCTOR_CHECK_DETAILS_EXISTS_CLEAR';
