export const PATIENT_EXERCISE_REQUEST = 'PATIENT_EXERCISE_REQUEST';
export const PATIENT_EXERCISE_SUCCESS = 'PATIENT_EXERCISE_SUCCESS';
export const PATIENT_EXERCISE_FAIL = 'PATIENT_EXERCISE_FAIL';

export const PATIENT_PENDING_EXERCISES_REQUEST =
  'PATIENT_PENDING_EXERCISES_REQUEST';
export const PATIENT_SELECTED_EXERCISE = 'PATIENT_SELECTED_EXERCISE';
