export const PATIENT_EXERCISE_REQUEST = 'PATIENT_EXERCISE_REQUEST';
export const PATIENT_EXERCISE_SUCCESS = 'PATIENT_EXERCISE_SUCCESS';
export const PATIENT_EXERCISE_FAIL = 'PATIENT_EXERCISE_FAIL';

export const PATIENT_PENDING_EXERCISES_REQUEST =
  'PATIENT_PENDING_EXERCISES_REQUEST';

export const PATIENT_SELECTED_EXERCISE = 'PATIENT_SELECTED_EXERCISE';

export const PATIENT_UPDATE_EXERCISE_STATS_REQUEST =
  'PATIENT_UPDATE_EXERCISE_STATS_REQUEST';
export const PATIENT_UPDATE_EXERCISE_STATS_SUCCESS =
  'PATIENT_UPDATE_EXERCISE_STATS_SUCCESS';
export const PATIENT_UPDATE_EXERCISE_STATS_FAIL =
  'PATIENT_UPDATE_EXERCISE_STATS_FAIL';
